import db from "@/shared/services/firebase/config";
import { setDoc, doc } from "firebase/firestore";

import React from "react";

type Props = {};

export const handleClubsCollection = async () => {
  clubs.forEach(async (club) => {
    await setDoc(doc(db, `clubs/${club.uuid}`), {
      name_th: club.name_th,
      name_eng: club.name_eng,
      club_type: club.club_type,
      club_fb: club.club_fb,
    });
  });
};

export default handleClubsCollection;

const clubs = [
  {
    name_th: "องค์การนักศึกษามหาวิทยาลัยขอนแก่น",
    name_eng: "Student Union",
    uuid: "student_union",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/kkustudentunion",
  },
  {
    name_th: "ชมรมนักศึกษาคริสเตียน",
    name_eng: "Christian Student Club",
    uuid: "christian_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/KKUChristian",
  },
  {
    name_th: "ชมรมผู้นำธรรมาภิบาล",
    name_eng: "Good Governance Leaders Club",
    uuid: "good_governance_leaders_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/GoodGovernancekku",
  },
  {
    name_th: "ชมรมพัฒนาผู้นำ",
    name_eng: "Leadership Development Club",
    uuid: "leadership_development_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/LDCKKU",
  },
  {
    name_th: "ชมรมประสานงานนักศึกษาเพื่อน้องผู้ด้อยโอกาสทางการศึกษา",
    name_eng:
      "Student Coordinating Club for Underprivileged Education Students",
    uuid: "student_underprivileged_education_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/PNNCLUBKKU",
  },
  {
    name_th: "ชมรมถ่ายภาพ",
    name_eng: "Photography Club",
    uuid: "photography_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/photokku",
  },
  {
    name_th: "ชมรมคุ้มครองผู้บริโภค",
    name_eng: "Consumer Protection Club",
    uuid: "consumer_protection_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/profile.php?id=100060216757198",
  },
  {
    name_th: "กรมนักศึกษาวิชาทหาร",
    name_eng: "Department of Military Student Affairs",
    uuid: "military_student_affairs",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/rotcskku",
  },
  {
    name_th: "ชมรมนักร้องประสานเสียง",
    name_eng: "Choir Club",
    uuid: "choir_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/kkuchorus",
  },
  {
    name_th: "ชมรมดนตรีและนาฏศิลป์ไทย",
    name_eng: "Thai Music and Dance Club",
    uuid: "thai_music_dance_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/Thaimusickkuclub",
  },
  {
    name_th: "ชมรมนักศึกษาเพื่อการพัฒนา",
    name_eng: "Student Development Club",
    uuid: "student_development_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/chornorpor",
  },
  {
    name_th: "ชมรมโรตาแรคท์",
    name_eng: "Rotaract Club",
    uuid: "rotaract_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/profile.php?id=100064572496634",
  },
  {
    name_th: "ชมรมปันรัก",
    name_eng: "Sharing Love Club",
    uuid: "sharing_love_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/panrakclub",
  },
  {
    name_th: "ชมรมนักศึกษาคริสเตียนนานาชาติ",
    name_eng: "International Christian Student Club",
    uuid: "international_christian_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/cslkkuclub",
  },
  {
    name_th: "ชมรมอาสาพัฒนา",
    name_eng: "Volunteer Development Club",
    uuid: "volunteer_development_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/asamohdindang",
  },
  {
    name_th: "ชมรมอีสาน",
    name_eng: "Isan Club",
    uuid: "isan_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/Esanclubkkufamily",
  },
  {
    name_th: "ชมรมผู้บำเพ็ญประโยชน์",
    name_eng: "Volunteer Club",
    uuid: "volunteer_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/profile.php?id=100064784226339",
  },
  {
    name_th: "ชมรมพี่ปันน้อง",
    name_eng: "Brother-Sister Sharing Club",
    uuid: "brother_sister_sharing_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/KKUmart6",
  },
  {
    name_th: "ชมรมอนุรักษ์สภาพแวดล้อมและทรัพยากร",
    name_eng: "Environment and Resources Conservation Club",
    uuid: "environment_resources_conservation_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/ConservationClubKKU",
  },
  {
    name_th: "ชมรพัฒนาอนามัย",
    name_eng: "Health Development Club",
    uuid: "health_development_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/profile.php?id=100064920150785",
  },
  {
    name_th: "ชมรมพยัคฆ์ วนค.",
    name_eng: "Tiger Club, Faculty of Forestry",
    uuid: "faculty_forestry_tiger_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/profile.php?id=100064765357069",
  },
  {
    name_th: "ชมรมสมาธิและศีลธรรม",
    name_eng: "Meditation and Morality Club",
    uuid: "meditation_morality_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/mmckku",
  },
  {
    name_th: "ชมรมนักศึกษาคาทอลิก",
    name_eng: "Catholic Student Club",
    uuid: "catholic_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/kkucatholic",
  },
  {
    name_th: "ชมรมมุสลิม",
    name_eng: "Muslim Club",
    uuid: "muslim_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/KKU.Muslim.Club",
  },
  {
    name_th: "ชมรมพุทธศาสน์และประเพณี",
    name_eng: "Buddhism and Tradition Club",
    uuid: "buddhism_tradition_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/kkubc.99",
  },
  {
    name_th: "ชมรมสืบสานวัฒนธรรมไทย-จีน",
    name_eng: "Thai-Chinese Cultural Heritage Club",
    uuid: "thai_chinese_cultural_heritage_club",
    club_type: "ชมรมและนันทนาการ",
    club_fb: "https://www.facebook.com/profile.php?id=61551085583418",
  },
  {
    name_th: "ชมรมวอลเลย์บอล",
    name_eng: "Volleyball Club",
    uuid: "volleyball_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/KKUVC",
  },
  {
    name_th: "ชมรมเทเบิลเทนนิส",
    name_eng: "Table Tennis Club",
    uuid: "table_tennis_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/KKU-TableTennis-Club-685882565079030/",
  },
  {
    name_th: "ชมรมเทนนิส",
    name_eng: "Tennis Club",
    uuid: "tennis_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/profile.php?id=100063484782705",
  },
  {
    name_th: "ชมรมเทควันโด",
    name_eng: "Taekwondo Club",
    uuid: "taekwondo_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/groups/619632311483126",
  },
  {
    name_th: "ชมรมเปตอง",
    name_eng: "Pétanque Club",
    uuid: "petanque_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/profile.php?id=100055188583294",
  },
  {
    name_th: "ชมรมเรือพาย",
    name_eng: "Rowing Club",
    uuid: "rowing_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/profile.php?id=100076348504859",
  },
  {
    name_th: "ชมรมแบดมินตัน",
    name_eng: "Badminton Club",
    uuid: "badminton_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/BADMINTONKKU",
  },
  {
    name_th: "ชมรมกรีฑา",
    name_eng: "Athletics Club",
    uuid: "athletics_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/profile.php?id=100030320876116",
  },
  {
    name_th: "ชมรมกีฬาทางน้ำ",
    name_eng: "Aquatic Club",
    uuid: "aquatic_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/profile.php?id=100093603555484",
  },
  {
    name_th: "ชมรมกีฬาอิเล็กทรอนิกส์ (e-Sport)",
    name_eng: "E-Sports Club",
    uuid: "esports_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/kkuesports/",
  },
  {
    name_th: "ชมรมครอสเวิร์ด",
    name_eng: "Crossword Club",
    uuid: "crossword_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/CrosswordKKU/",
  },
  {
    name_th: "ชมรมซอฟท์บอล",
    name_eng: "Softball Club",
    uuid: "softball_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/softballkkuclub/",
  },
  {
    name_th: "ชมรมตะกร้อ",
    name_eng: "Sepak Takraw Club",
    uuid: "sepak_takraw_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/profile.php?id=100063466332837",
  },
  {
    name_th: "ชมรมบริดจ์",
    name_eng: "Bridge Club",
    uuid: "bridge_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/profile.php?id=100063470110289",
  },
  {
    name_th: "ชมรมบาสเกตบอล",
    name_eng: "Basketball Club",
    uuid: "basketball_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/KKUBasketballClub",
  },
  {
    name_th: "ชมรมฟันดาบ",
    name_eng: "Fencing Club",
    uuid: "fencing_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/Fencing.kku/",
  },
  {
    name_th: "ชมรมฟุตซอล",
    name_eng: "Futsal Club",
    uuid: "futsal_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/futsalkhonkeanuniversity",
  },
  {
    name_th: "ชมรมฟุตบอล",
    name_eng: "Football Club",
    uuid: "football_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/kkufc1/",
  },
  {
    name_th: "ชมรมยิงธนู",
    name_eng: "Archery Club",
    uuid: "archery_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/kkuarchery/",
  },
  {
    name_th: "ชมรมยิงปืน",
    name_eng: "Shooting Club",
    uuid: "shooting_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/KKUshootingclub",
  },
  {
    name_th: "ชมรมยูโด",
    name_eng: "Judo Club",
    uuid: "judo_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/judokku",
  },
  {
    name_th: "ชมรมรักบี้ฟุตบอล",
    name_eng: "Rugby Football Club",
    uuid: "rugby_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/KkuRugbyClub",
  },
  {
    name_th: "ชมรมคริกเก็ต",
    name_eng: "Cricket Club",
    uuid: "cricket_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/cricketkku",
  },
  {
    name_th: "ชมรมหมากกระดาน",
    name_eng: "Board Games Club",
    uuid: "board_games_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/groups/1000925316677290",
  },
  {
    name_th: "ชมรมฮอกกี้",
    name_eng: "Hockey Club",
    uuid: "hockey_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/hockeyKKU",
  },
  {
    name_th: "ชมรมมวย",
    name_eng: "Boxing Club",
    uuid: "boxing_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "https://www.facebook.com/kkuboxing",
  },
  {
    name_th: "ชมรมจารร่อน",
    name_eng: "Frisbee Club",
    uuid: "frisbee_club",
    club_type: "ชมรมด้านกีฬา",
    club_fb: "N/A",
  },
];
